obj-$(CONFIG_MMP_PANEL_TPOHVGA)    += tpo_tj032md01bw.o
obj-$(CONFIG_MMP_PANEL_R63311)     += mipi_r63311.o
obj-$(CONFIG_MMP_PANEL_LG4591)     += mipi_lg4591.o
obj-$(CONFIG_MMP_PANEL_HX8394_IPS3P5071)     += mipi_hx8394_ips3p5071.o
