ccflags-y += -Idrivers/marvell/marvell-telephony/errorhandler
ccflags-y += -Idrivers/marvell/marvell-telephony/m3_rm
msocketk-objs := portqueue.o shm.o msocket.o acipcd.o data_path.o direct_rb.o amipcd.o psd_data_channel.o
obj-$(CONFIG_MRVL_MMP_MODEM)	+= msocketk.o
