ccflags-y += -Idrivers/marvell/marvell-telephony/errorhandler
ccflags-y += -Idrivers/marvell/marvell-telephony/m3_rm
msocketk-objs := portqueue.o msocket.o acipcd.o direct_rb.o amipcd.o
obj-$(CONFIG_MRVL_MMP_MODEM)	+= msocketk.o
