obj-y				:= dma-mapping-nc.o dma-iommu-mapping.o \
				   extable.o fault.o init.o \
				   cache.o copypage.o flush.o \
				   ioremap.o mmap.o pgd.o mmu.o \
				   context.o tlb.o proc.o
obj-$(CONFIG_HUGETLB_PAGE)	+= hugetlbpage.o
