#
# Makefile for the drivers of Marvell devices.
#

obj-$(CONFIG_MRVL_DEBUG) += debug/
obj-$(CONFIG_MRVL_PANIC_FLUSH) += emmd/
obj-$(CONFIG_MRVL_SW_JTAG) += sw_jtag/
obj-$(CONFIG_MRVL_SKMALLOC) += kmalloc/
obj-$(CONFIG_MRVL_MMP_MODEM) += marvell-telephony/
