#
# Makefile for mach
#

obj-y	+= mmpx-dt.o helanx-dt.o regs-addr.o pxa1908_lowpower.o pxa1928_lowpower.o pm.o pm-pxa1928.o pm-pxa1908.o soc_camera_dkb.o
obj-$(CONFIG_CORESIGHT_SUPPORT)	+= coresight-v8.o
