# Makefile for MARVELL MMP ISP driver

# TODO: Add platform Camera/ISP driver below
obj-$(CONFIG_VIDEO_MMPISP_B52SENSOR) += b52-sensor.o
obj-$(CONFIG_VIDEO_MMPISP_B52) += b52-reg.o b52isp-ctrl.o b52isp.o
obj-$(CONFIG_VIDEO_MMPISP_CCICV2) += ccicv2.o
obj-$(CONFIG_VIDEO_MMPISP_PLATFORM) += plat_cam.o

obj-$(CONFIG_VIDEO_MMPISP) += b52socisp/
