obj-y					+= pm_domain.o

obj-$(CONFIG_MMP_PM_DOMAIN_COMMON)	+= pd_common.o
obj-$(CONFIG_MMP_PM_DOMAIN_SC2_ISP) += pd_sc2_isp.o
obj-$(CONFIG_MMP_PM_DOMAIN_DISPLAY)	+= pd_display.o
obj-$(CONFIG_MMP_PM_DOMAIN_HANTRO)	+= pd_hantro.o
